apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rulo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-rulo@sha256:7f0360d247281c53cf0ec126abecc12bb6507f455319fa36b5f167fb26a966ee
        name: my-nodejs
        resources: {}
status: {}
